# Complete Manifest Where in single yml we defined Deployment & Service for SpringApp &
#PVC(with default  StorageClass),ReplicaSet/StatefulSet & Service For Mongo.
# storage class, pv, pvc, 
# configMaps / Secretes
apiVersion: v1
kind: Namespace
metadata:
  name: jatto-springapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-springapp
  template:
    metadata:
      name: springapp-deployment
      labels:
        app: app-springapp
    spec:
      containers:
      - name: springappcontainer
        image: charlesjatto/spring-boot-mongo:v4
        ports:
        - containerPort: 80
        env:
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123
        - name: MONGO_DB_HOSTNAME
          value: mongo 
---
apiVersion: v1
kind: Service
metadata:
  name: springapp-service
spec:
  selector:
    app: app-springapp
  ports:
  - port: 80
    targetPort: 80
    ## nodePort: 30030
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbpvc 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
     metadata:
       name: mongodbpod
       labels:
         app: mongodb
     spec:
       volumes:
       - name: pvc
         persistentVolumeClaim:
           claimName: mongodbpvc     
       containers:
       - name: mongodbcontainer
         image: mongo
         ports:
         - containerPort: 27017
         env:
         - name: MONGO_INITDB_ROOT_USERNAME
           value: devdb
         - name: MONGO_INITDB_ROOT_PASSWORD
           value: devdb@123
         volumeMounts:
         - name: pvc
           mountPath: /data/db   
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
