# Complete Manifest Where in single yml we defined Deployment & Service for SpringApp &
#PVC(with default  StorageClass),ReplicaSet/StatefulSet & Service For Mongo.
# storage class, pv, pvc, 
# configMaps / Secretes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deployment
  namespace: jatto-springapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-springapp
  template:
    metadata:
      name: springapp-deployment
      labels:
        app: app-springapp
    spec:
      containers:
      - name: springappcontainer
        image: charlesjatto/spring-boot-mongo
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123
        - name: MONGO_DB_HOSTNAME
          value: mongo 
---
apiVersion: v1
kind: Service
metadata:
  name: service-springapp
spec:
  selector:
    app: app-springapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30030
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: jatto-springapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb@123
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: jatto-springapp
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
